name: PowerEssentials
main: angga7togk\poweressentials\PowerEssentials
api: 5.0.0
version: 1.0.0
author: Angga7Togk

permissions:
  poweressentials.setlobby:
    default: op
  poweressentials.lobby:
    default: true
  poweressentials.fly:
    default: op
  poweressentials.fly.other:
    default: op
  poweressentials.antinamespace.bypass:
    default: op
