##################################
#         PowerEssentials        #
##################################
# You can customize your own language via the language folder, just create it
# example = id.yml
# then change here to 'id'
language: en

# on join force set gamemode
gamemode-join-enable: true
gamemode-join: SURVIVAL

# on join force spawn to lobby position
spawn-lobby-join: true

# Players with space names are prohibited from entering
anti-namespace: false

##################################
#            Nicknames           #
##################################
# maximum number of characters
nickname-max-char: 15

# blacklist nickname
# This feature only works for /nickname
blacklist-nicknames:
  - admin
  - owner
  - staff

##################################
#            Commands            #
##################################
# commands option disable and enabled
# set false to disable
# set true to enable
commands:
  lobby: true
  fly: true
  gamemode: true
  nickname: true
